server:
  port: 8080
  
http:
    end-point: /core-base  
    
management:
   endpoints:
      web:
         exposure:
            include: info, health , mappings , integrationgraph , caches , conditions , metrics

spring:
  activemq:
   broker-url: tcp://localhost:61616
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5434/musicbrainz
    url: jdbc:postgresql://127.0.0.1:5434/musicbrainz
    username: postgres 
    password: postgres123@   
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 10000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
        javax:
         cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
        cache:
           use_second_level_cache: true
           use_query_cache: true
           region:
              factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  ehcache:
      config: classpath:ehcache.xml                  
  properties:
    javax:
      persistence:
        sharedCache: 
            #required - enable selective caching mode - only entities with @Cacheable annotation will use L2 cache.
        mode: ENABLE_SELECTIVE         

entitymanager:
  packagesToScan: org.nanotek

config:
  fileLocation: /opt/mbdump
  fileName: artist_head_dump
  immutable: org.nanotek.beans.csv.ArtistBean
  baseMap:
    artistId: 0
    gid: 1
    artistName: 2
    sortName: 3
    beginDateYear: 4
    beginDateMonth: 5
    beginDateDay: 6
    endDateYear: 7
    endDateMonth: 8
    endDateDay: 9
    typeId: 10
    areaId: 11
    genderId: 12 
    comment: 13
    editsPending: 14
    lastUpdated: 15
    ended: 16
    beginAreaId: 17
    endAreaId: 18

    
    
artist:
  fileLocation: /opt/mbdump
  fileName: artist_head_dump
  immutable: org.nanotek.beans.csv.ArtistBean
  baseMap:
    artistId: 0
    gid: 1
    artistName: 2
    sortName: 3
    beginDateYear: 4
    beginDateMonth: 5
    beginDateDay: 6
    endDateYear: 7
    endDateMonth: 8
    endDateDay: 9
    typeId: 10
    areaId: 11
    genderId: 12 
    comment: 13
    editsPending: 14
    lastUpdated: 15
    ended: 16
    beginAreaId: 17
    endAreaId: 18

area: 
  fileLocation: /opt/mbdump
  fileName: area_dump1
  immutable: org.nanotek.beans.csv.AreaBean
  baseMap:     
    areaId: 0 
    gid: 1 
    areaName: 2 
    typeId: 3 
    editsPending: 4 
    lastUpdated: 5 
    beginYear: 6 
    beginMonth: 7 
    beginDay: 8 
    endYear: 9 
    endMonth: 10 
    endDay: 11
    ended: 12 
    comment: 13   
    
areatype: 
  fileLocation: /opt/mbdump
  fileName: area_type
  immutable: org.nanotek.beans.csv.AreaTypeBean  
  baseMap:     
    typeId: 0
    typeName: 1
    parent: 2
    childOrder: 3
    description: 4
    gid: 5 
    
artistaliastype: 
  fileLocation: /opt/mbdump
  fileName: artist_alias_type
  immutable: org.nanotek.beans.csv.ArtistAliasTypeBean
  baseMap:     
    artistAliasTypeId: 0
    typeName: 1
    parent: 2
    child_order: 3
    description: 4
    gid: 5       
    
    
artistalias:
  fileLocation: /opt/mbdump
  fileName: artist_alias_dump
  immutable: org.nanotek.beans.csv.ArtistAliasBean
  baseMap:  
    aliasId: 0
    artistId: 1
    artistAliasName: 2
    locale: 3
    editsPending: 4
    lastUpdated: 5
    typeId: 6
    sortName: 7
    beginYear: 8
    beginMonth: 9
    beginDay: 10
    endYear: 11
    endMonth: 12
    endDay: 13
    primaryForLocale: 14
    ended: 15    
 
artistcredit:
  fileLocation: /opt/mbdump
  fileName: artist_credit_dump
  immutable: org.nanotek.beans.csv.ArtistCreditBean
  baseMap:  
    artistCreditId: 0
    artistCreditName: 1
    count: 2
    refCount: 3
    created: 4
    editsPending: 5   
    
artistcreditedname:
  fileLocation: /opt/mbdump
  fileName: artist_credit_name_dump
  immutable: org.nanotek.beans.csv.ArtistCreditNameBean
  baseMap:  
    artistCreditId: 0
    position: 1            
    artistId: 2              
    artistCreditedName: 3                
    artistCreditedNameJoinPhrase: 4     
    