server:
  port: 8080
  
http:
    end-point: /core-base  
    
management:
   endpoints:
      web:
         exposure:
            include: info, health , mappings , integrationgraph , caches , conditions , metrics
    
spring:
  activemq:
   broker-url: tcp://localhost:61616
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5434/musicbrainz
    url: jdbc:postgresql://127.0.0.1:5434/musicbrainz
    username: postgres 
    password: postgres123@   
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 100
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        ddl-auto: create-drop
        javax:
         cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
        cache:
           use_second_level_cache: true
           use_query_cache: true
           region:
              factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  ehcache:
      config: classpath:ehcache.xml                  
  properties:
    javax:
      persistence:
        sharedCache: 
            #required - enable selective caching mode - only entities with @Cacheable annotation will use L2 cache.
        mode: ENABLE_SELECTIVE         

entitymanager:
  packagesToScan: org.nanotek

artist:
  fileLocation: /opt/mbdump
  fileName: artist
  baseMapColumnStrategy:
    artistId: 0
    gid: 1
    name: 2
    sortName: 3
    beginDateYear: 4
    beginDateMonth: 5
    beginDateDay: 6
    endDateYear: 7
    endDateMonth: 8
    endDateDay: 9
    type: 10
    area: 11
    gender: 12 
    comment: 13
    editsPending: 14
    lastUpdated: 15
    ended: 16
    beginArea: 17
    endArea: 18

    
artistalias:
  fileLocation: /opt/mbdump
  fileName: artist_alias
  baseMapColumnStrategy:  
    artistAliasId: 0
    artistId: 1
    name: 2
    locale: 3
    editsPending: 4
    lastUpdated: 5
    type: 6
    sortName: 7
    beginDateYear: 8
    beginDateMonth: 9
    beginDateDay: 10
    endDateYear: 11
    endDateMonth: 12
    endDateDay: 13
    primaryForLocale: 14
    ended: 15
    
artistcredit:
  fileLocation: /opt/mbdump
  fileName: artist_credit1
  baseMapColumnStrategy:  
    artistCreditId: 0
    name: 1
    artistCount: 2
    refCount: 3
    created: 4
    editsPending: 5

artistcreditname:
  fileLocation: /opt/mbdump
  fileName: artist_credit_name
  baseMapColumnStrategy:  
    artistCreditId: 0
    position: 1            
    artist: 2              
    name: 3                
    joinPhrase: 4    
 
artistcreditnamebean:
  fileLocation: /opt/mbdump
  fileName: artist_credit_name
  baseMapColumnStrategy:  
    artistCreditId: 0
    position: 1            
    artistId: 2              
    name: 3                
    joinPhrase: 4      
    
releasebean: 
  fileLocation: /opt/mbdump/release_cut
  fileName: release_ah
  baseMapColumnStrategy: 
    releaseId: 0 
    gid: 1 
    name: 2
    artistCreditId: 3 
    releaseGroup: 4 
    status: 5 
    packaging: 6 
    language: 7 
    script: 8
    barcode: 9 
    comment: 10 
    editsPending: 11 
    quality: 12 
    lastUpdated: 13
    
releasegroup: 
  fileLocation: /opt/mbdump
  fileName: release_group
  baseMapColumnStrategy:   
    releaseGroupId: 0 
    gid: 1 
    name: 2 
    artistCredit: 3 
    type: 4
    comment: 5 
    editsPending: 6
    lastUpdated: 7
 
recordingbean: 
  fileLocation: /opt/mbdump/recording_split
  fileName: recaa
  baseMapColumnStrategy:   
    recordingId: 0
    gid: 1
    name: 2
    artistCredit: 3
    length: 4
    comment: 5
    editsPending: 6
    lastUpdated: 7
    video: 8

trackbean: 
  fileLocation: /opt/mbdump
  fileName: track
  baseMapColumnStrategy:    
    trackId: 0 
    gid: 1 
    recordingId: 2 
    medium: 3 
    position: 4 
    number: 5 
    name: 6 
    artistCreditId: 7 
    length: 8 
    editsPending: 8 
    lastUpdate: 9
    isDataTrack: 10
    
mediumbean: 
  fileLocation: /opt/mbdump
  fileName: medium
  baseMapColumnStrategy:     
    mediumId: 0
    release: 1 
    position: 2
    format: 3 
    name: 4 
    editsPending: 5 
    lastUpdated: 6 
    trackCount: 7 
    
artisttype: 
  fileLocation: /opt/mbdump
  fileName: artist_type
  baseMapColumnStrategy:     
    artistTypeId: 0
    name: 1
    parent: 2
    child_order: 3
    description: 4
    gid: 5
    
artistaliastype: 
  fileLocation: /opt/mbdump
  fileName: artist_alias_type
  baseMapColumnStrategy:     
    artistAliasTypeId: 0
    name: 1
    parent: 2
    child_order: 3
    description: 4
    gid: 5    

instrumenttype:
  fileLocation: /opt/mbdump
  fileName: instrument_type
  baseMapColumnStrategy:     
    instrumentTypeId: 0
    name: 1
    parent: 2
    child_order: 3
    description: 4
    gid: 5

instrument:
  fileLocation: /opt/mbdump
  fileName: instrument
  baseMapColumnStrategy:     
    instrumentId: 0
    gid: 1
    name: 2
    type: 3
    editsPending: 4
    lastUpdatead: 5
    comment: 6 
    description: 7

releasegroupprimarytype:
  fileLocation: /opt/mbdump
  fileName: release_group_primary_type
  baseMapColumnStrategy:  
      releaseGroupPrimaryTypeId: 0 
      name: 1 
      parent: 2 
      childOrder: 3 
      description: 4 
      gid: 5
      
releasestatus:
  fileLocation: /opt/mbdump
  fileName: release_status
  baseMapColumnStrategy:  
      releaseStatusId: 0 
      name: 1 
      parent: 2 
      childOrder: 3 
      description: 4 
      gid: 5 

releasepackaging:
  fileLocation: /opt/mbdump
  fileName: release_packaging
  baseMapColumnStrategy:  
      releasePackagingId: 0 
      name: 1 
      parent: 2 
      childOrder: 3 
      description: 4 
      gid: 5            

language:
  fileLocation: /opt/mbdump
  fileName: language
  baseMapColumnStrategy:  
      languageId: 0 
      isoCode2t: 1 
      isoCode2b: 2 
      isoCode1: 3 
      name: 4 
      frequency: 5 
      isoCode3: 6            

areatype: 
  fileLocation: /opt/mbdump
  fileName: area_type
  baseMapColumnStrategy:     
    areaTypeId: 0
    name: 1
    parent: 2
    child_order: 3
    description: 4
    gid: 5
    
gendertype: 
  fileLocation: /opt/mbdump
  fileName: gender
  baseMapColumnStrategy:     
    genderTypeId: 0
    name: 1
    parent: 2
    child_order: 3
    description: 4
    gid: 5    

releasealiastype: 
  fileLocation: /opt/mbdump
  fileName: release_alias_type
  baseMapColumnStrategy:     
    releaseAliasTypeId: 0
    name: 1
    parent: 2
    child_order: 3
    description: 4
    gid: 5

recordingaliastype:
  fileLocation: /opt/mbdump
  fileName: recording_alias_type
  baseMapColumnStrategy:     
    recordingAliasTypeId: 0
    name: 1
    parent: 2
    child_order: 3
    description: 4
    gid: 5

area: 
  fileLocation: /opt/mbdump
  fileName: area
  baseMapColumnStrategy:     
    areaId: 0 
    gid: 1 
    name: 2 
    type: 3 
    editsPending: 4 
    lastUpdated: 5 
    beginDateYear: 6 
    beginDateMonth: 7 
    beginDateDay: 8 
    endDateYead: 9 
    endDateMonth: 10 
    endDateDay: 11
    ended: 12 
    comment: 13 
    
releasealias: 
  fileLocation: /opt/mbdump
  fileName: release_alias
  baseMapColumnStrategy:     
    releaseAliasId: 0 
    release: 1 
    name: 2 
    locale: 3 
    editsPending: 4 
    lastUpdated: 5 
    type: 6
    sortName: 7
    beginDateYear: 8 
    beginDateMonth: 9 
    beginDateDay: 10
    endDateYead: 11 
    endDateMonth: 12 
    endDateDay: 13
    primaryForLocale: 14 
    ended: 15 
    
recordingalias: 
  fileLocation: /opt/mbdump
  fileName: recording_alias
  baseMapColumnStrategy:     
    recordingAliasId: 0 
    release: 1 
    name: 2 
    locale: 3 
    editsPending: 4 
    lastUpdated: 5 
    type: 6
    sortName: 7
    beginDateYear: 8 
    beginDateMonth: 9 
    beginDateDay: 10
    endDateYead: 11 
    endDateMonth: 12 
    endDateDay: 13
    primaryForLocale: 14 
    ended: 15     

mediumformat: 
  fileLocation: /opt/mbdump
  fileName: medium_format
  baseMapColumnStrategy:     
    mediumFormatId: 0
    name: 1
    parent: 2
    child_order: 3
    year: 4
    hasDiscIds: 5
    description: 5
    gid: 6
    
csv-endpoint:
   instrument-type: /csv/instrument 
   map-config: /map_config
   reopen: /reopen_file
   next: /next
   next_entity: /next_entity
   load: /load
