server:
  port: 8080

config:
  fileLocation: /opt/mbdump
  fileName: artist
  immutable: org.nanotek.beans.csv.ArtistBean
  baseMap:
    artistId: 0
    gid: 1
    name: 2
    sortName: 3
    beginDateYear: 4
    beginDateMonth: 5
    beginDateDay: 6
    endDateYear: 7
    endDateMonth: 8
    endDateDay: 9
    type: 10
    area: 11
    gender: 12 
    comment: 13
    editsPending: 14
    lastUpdated: 15
    ended: 16
    beginArea: 17
    endArea: 18
