create sequence artist_credit_name_id_seq start 1 increment 50;
create sequence isrc_id_seq start 1 increment 50;
create sequence sequence_id_seq start 1 increment 50;
create table area (area_id int8 not null, id int8 not null, type_id int8 not null, primary key (id));
create table area_begin_date_join (date_id int8, area_id int8 not null, primary key (area_id));
create table area_comment_join (comment_id int8, area_id int8 not null, primary key (area_id));
create table area_end_date_join (date_id int8, area_id int8 not null, primary key (area_id));
create table AreaType (id int8 not null, primary key (id));
create table artist (artist_id int8 not null, id int8 not null, type_id int8 not null, primary key (id));
create table artist_alias (artist_alias_id int8 not null, id int8 not null, primary key (id));
create table artist_alias_begin_date_join (date_id int8, artist_alias_id int8 not null, primary key (artist_alias_id));
create table artist_alias_end_date_join (date_id int8, artist_alias_id int8 not null, primary key (artist_alias_id));
create table artist_alias_join (artist_id int8 not null, artist_alias_id int8 not null, primary key (artist_alias_id));
create table artist_alias_locale_join (locale_id int8, artist_alias_id int8 not null, primary key (artist_alias_id));
create table artist_alias_sortname_join (sort_name_id int8 not null, artist_alias_id int8 not null, primary key (artist_alias_id));
create table artist_alias_type_join (alias_type_id int8 not null, artist_alias_id int8 not null, primary key (artist_alias_id));
create table artist_area_join (area_id int8, artist_id int8 not null, primary key (artist_id));
create table artist_begin_area_join (area_id int8, artist_id int8 not null, primary key (artist_id));
create table artist_begin_date_join (date_id int8, artist_id int8 not null, primary key (artist_id));
create table artist_comment_join (comment_id int8, artist_id int8 not null, primary key (artist_id));
create table artist_credit (artist_credit_id int8 not null, id int8 not null, primary key (id));
create table artist_credit_count_join (artist_count_id int8 not null, artist_credit_id int8 not null, primary key (artist_credit_id));
create table artist_credit_name (id int8 not null, artist_credit_name_join_prase varchar(2000), ARTIST_NAME varchar(1000), ARTIST_CREDIT_NAME_POSITION int8, artistid int8, artist_credit_id int8, primary key (id));
create table artist_credit_name_rel (artist_credit_id int8 not null, artist_name_id int8 not null);
create table artist_end_area_join (area_id int8, artist_id int8 not null, primary key (artist_id));
create table artist_end_date_join (date_id int8, artist_id int8 not null, primary key (artist_id));
create table artist_gender_join (gender_id int8, artist_id int8 not null, primary key (artist_id));
create table artist_ref_count_join (artist_refcount_id int8 not null, artist_credit_id int8 not null, primary key (artist_credit_id));
create table artist_sortname_join (sort_name_id int8 not null, artist_id int8 not null, primary key (artist_id));
create table ArtistAliasType (id int8 not null, primary key (id));
create table ArtistType (id int8 not null, primary key (id));
create table bar_code_base (table_id VARCHAR NOT NULL not null, id int8 not null, bar_code varchar(255) not null, primary key (id));
create table base_type (childOrder int8, parent int8, type_id int8, id int8 not null, primary key (id));
create table base_type_description_join (description_id int8, base_type_id int8 not null, primary key (base_type_id));
create table comment_base (table_id VARCHAR NOT NULL not null, id int8 not null, comment VARCHAR NOT NULL not null, primary key (id));
create table composite_dates (table_id VARCHAR NOT NULL not null, id int8 not null, day int4, month int4, year int4 not null, primary key (id));
create table description_base (table_id VARCHAR NOT NULL not null, id int8 not null, description VARCHAR NOT NULL not null, primary key (id));
create table description_comment_join (description_id int8, instrument_id int8 not null, primary key (instrument_id));
create table Gender (id int8 not null, primary key (id));
create table instrument (instrument_id int8 not null, id int8 not null, type_id int8 not null, primary key (id));
create table instrument_comment_join (comment_id int8, instrument_id int8 not null, primary key (instrument_id));
create table InstrumentType (id int8 not null, primary key (id));
create table InstrumentType_instrument (InstrumentType_id int8 not null, instruments_id int8 not null, primary key (InstrumentType_id, instruments_id));
create table isrc (id int8 not null, ISRC varchar(255), ISRC_ID int8, RECORDING_ID int8, SOURCE varchar(255), primary key (id));
create table label (id int8 not null, beginDateDay varchar(255), beginDateMonth varchar(255), beginDateYear varchar(255), country varchar(255), endDateDay varchar(255), endDateMonth varchar(255), endDateYear varchar(255), gid varchar(255), ipiCode varchar(255), labelCode varchar(255), labelId int8, name int8, sortName int8, type varchar(255), primary key (id));
create table language (frequency int8, isoCode1 varchar(2), isoCode2b varchar(3), isoCode2t varchar(3), isoCode3 varchar(3), language_id int8, id int8 not null, primary key (id));
create table locale_base (table_id VARCHAR NOT NULL not null, id int8 not null, locale VARCHAR NOT NULL, primary key (id));
create table long_count_base (table_id VARCHAR NOT NULL not null, id int8 not null, count int8 not null, primary key (id));
create table long_id_gid_name (gid varchar(50) not null, id int8 not null, primary key (id));
create table long_id_name (id int8 not null, name VARCHAR NOT NULL not null, primary key (id));
create table long_lengthy_base (table_id VARCHAR NOT NULL not null, id int8 not null, length int8 not null, track_id int8 not null, primary key (id));
create table long_number_base (table_id VARCHAR NOT NULL not null, id int8 not null, number int8 not null, primary key (id));
create table long_position_base (table_id VARCHAR NOT NULL not null, id int8 not null, position int8 not null, primary key (id));
create table Medium (medium_id int8, id int8 not null, medium_format_id int8 not null, release_id int8 not null, primary key (id));
create table medium_count_join (position_id int8 not null, medium_id int8 not null, primary key (medium_id));
create table medium_format (id int8 not null, description varchar(4000), gid varchar(50) not null, hasDiscId varchar(6) not null, name varchar(100) not null, parent int8, year int4, primary key (id));
create table medium_position_join (position_id int8 not null, medium_id int8 not null, primary key (medium_id));
create table recording (recording_id int8 not null, id int8 not null, artist_credit_id int8 not null, recordingLenght_id int8, primary key (id));
create table recording_alias (id int8 not null, begin_date_day int4, begin_date_month int4, begin_date_year int4, end_date_day int4, end_date_month int4, end_date_year int4, locale varchar(1000), name varchar(1000) not null, sortName varchar(1000) not null, recording_id int8 not null, recording_type_id int8, primary key (id));
create table RecordingAliasType (id int8 not null, primary key (id));
create table release (release_id int8 not null, id int8 not null, artist_credit_id int8, language_id int8, packaging_id int8, release_group_id int8 not null, status_id int8, primary key (id));
create table release_alias (relase_alias_id int8 not null, id int8 not null, release_id int8 not null, type_id int8 not null, primary key (id));
create table release_alias_begin_date_join (date_id int8, release_alias_id int8 not null, primary key (release_alias_id));
create table release_alias_end_date_join (date_id int8, release_alias_id int8 not null, primary key (release_alias_id));
create table release_alias_locale_join (locale_id int8, release_alias_id int8 not null, primary key (release_alias_id));
create table release_alias_sortname_join (sortname_id int8 not null, release_alias_id int8 not null, primary key (release_alias_id));
create table release_barcode_join (barcode_id int8, release_id int8 not null, primary key (release_id));
create table release_comment_join (barcode_id int8, release_id int8 not null, primary key (release_id));
create table release_group (release_group_id int8 not null, id int8 not null, artist_credit_id int8 not null, type_id int8, primary key (id));
create table release_group_primary_type (id int8 not null, gid varchar(50) not null, name varchar(255) not null, primary key (id));
create table release_packaging (release_packaging_id int8 not null, id int8 not null, primary key (id));
create table release_status (release_status_id int8 not null, id int8 not null, primary key (id));
create table ReleaseAliasType (id int8 not null, primary key (id));
create table sort_name_base (table_id VARCHAR NOT NULL not null, id int8 not null, sort_name VARCHAR NOT NULL not null, primary key (id));
create table string_number_base (table_id VARCHAR NOT NULL not null, id int8 not null, number VARCHAR NOT NULL, primary key (id));
create table track (track_id int8, id int8 not null, artistCredit_id int8 not null, medium_id int8 not null, recordingId int8 not null, primary key (id));
create table track_length_join (length_id int8 not null, track_id int8 not null, primary key (track_id));
create table track_number_join (number_id int8 not null, track_id int8 not null, primary key (track_id));
create table track_position_join (position_id int8, track_id int8 not null, primary key (track_id));
alter table area add constraint uk_area_id unique (area_id);
alter table artist add constraint uk_artist_id unique (artist_id);
alter table artist_alias add constraint uk_artist_alias_id unique (artist_alias_id);
alter table artist_alias_sortname_join add constraint UK_pj758kjmvfi4w6iylmqqyf87y unique (sort_name_id);
alter table artist_credit add constraint uk_artist_credit_id unique (artist_credit_id);
alter table artist_credit_count_join add constraint UK_b1e6iatyc0a9ebcsnt02cmy6v unique (artist_count_id);
alter table artist_ref_count_join add constraint UK_cjp45m8pm8reo0nj52n626alp unique (artist_refcount_id);
alter table artist_sortname_join add constraint UK_tcbnii28trkvjw0for5lvukji unique (sort_name_id);
create index bar_code_idx on bar_code_base (bar_code);
create index base_type_id_idx on base_type (type_id);
create index comment_table_idx on comment_base (comment);
create index date_year_idx on composite_dates (year);
create index description_table_idx on description_base (description);
create index description_table_id_idx on description_base (table_id);
alter table language add constraint uk_language_id unique (language_id);
create index locale_table_idx on locale_base (locale);
create index long_count_field_idx on long_count_base (count);
alter table long_id_gid_name add constraint uk_id_gid_name unique (gid);
alter table long_lengthy_base add constraint UK_ns2jmpxdohnw34m6eqpj9q5ny unique (track_id);
create index long_position_position_idx on long_position_base (position);
create index long_position_table_idx on long_position_base (table_id);
alter table Medium add constraint uk_medium_id unique (medium_id);
alter table medium_count_join add constraint UK_r7raky87e1ui5csktub3ecdco unique (position_id);
alter table recording add constraint uk_recording_id unique (recording_id);
alter table release add constraint uk_release_id unique (release_id);
alter table release_group add constraint uk_release_group_id unique (release_group_id);
alter table release_packaging add constraint uk_release_pack_id unique (release_packaging_id);
alter table release_status add constraint uk_release_status_id unique (release_status_id);
alter table track_length_join add constraint UK_scyko933yrk07ctctpybraddq unique (length_id);
alter table track_number_join add constraint UK_fnkrp16hmvam21nqghfptddt5 unique (number_id);
