alter table area drop constraint FKkh7fglo0ew1ivq3g17l0v3xb9
alter table area_begin_date_join drop constraint FK6ejxgqiu1outyxf4qd2xqjfmj
alter table area_begin_date_join drop constraint FKhxwhfi68h7pm6nw99q60kulwx
alter table area_comment_join drop constraint FKa87l53y4i7o3ifexsbvp5a299
alter table area_comment_join drop constraint FKifb9goxbil6mp8qnlc652fg1o
alter table area_end_date_join drop constraint FKn5c0biposrf655qxo4s7hqk9i
alter table area_end_date_join drop constraint FK2to1rsv7q6jo3oh51adue24sq
alter table artist drop constraint FKnh2erfii5bjj6jjcbboporlhy
alter table artist_alias_begin_date_join drop constraint FK161ni63md650a9ws8jl6xsln6
alter table artist_alias_begin_date_join drop constraint FKpks05cos5wm1vmqr2pyjt97sf
alter table artist_alias_end_date_join drop constraint FKhvbnqkhq3q16g955k1uvepvxn
alter table artist_alias_end_date_join drop constraint FKmug4f2wcro7htgp48a4iwycu8
alter table artist_alias_join drop constraint FKgdwpq8ctk6a39mvnvsvo2fc5i
alter table artist_alias_join drop constraint FK48r5krvgiw047ms72erpsxkju
alter table artist_alias_locale_join drop constraint FKb6xi7sb9l8h80v4qdb52gewf2
alter table artist_alias_locale_join drop constraint FKtle5378eltgllln6n2jimbrrd
alter table artist_alias_sortname_join drop constraint FKtnhfe96x3gvwohh93u88harun
alter table artist_alias_sortname_join drop constraint FKaljjsn3xplko82gxwoyvnhhdg
alter table artist_alias_type_join drop constraint FK27j0hv1oggic0lv0fkjttcage
alter table artist_alias_type_join drop constraint FKp27ue68w73pcnl22m8cmvopjk
alter table artist_area_join drop constraint FK5v2pynxsg5phk81a9a888f8p6
alter table artist_area_join drop constraint FKjwws3jf2jrltwhscmyr4c2c8d
alter table artist_begin_area_join drop constraint FKlib6g7ixl78iper28hwyp4b6j
alter table artist_begin_area_join drop constraint FKdsqb47nv5mkfer33g0uwjxrg3
alter table artist_begin_date_join drop constraint FKkb756u3kpj2k4f9o3ar54uk5b
alter table artist_begin_date_join drop constraint FK9ep35foih1qqx5cvjt9lwa1gy
alter table artist_comment_join drop constraint FK5sh23cs6j9tv0i8yta3nldxpw
alter table artist_comment_join drop constraint FKtqvsp3t5j61w068n51iowndiw
alter table artist_credit_count_join drop constraint FKf79dl4q17hswqhv9y4mb65qat
alter table artist_credit_count_join drop constraint FK9pp1ahlexg9hgppy4p3eeit7y
alter table artist_credit_name_position_join drop constraint FKonl1oigpxdolrcy2vxqi308lr
alter table artist_credit_name_position_join drop constraint FK92reeafxnwbh56ucuujcip32m
alter table artist_credit_name_rel drop constraint FKn3g0jyj028jrwt6ckpuvk1y5j
alter table artist_credit_name_rel drop constraint FK44fgvkqt29bcp2ai5oewfl4p1
alter table artist_end_area_join drop constraint FKdq9xln44yycsfyifwjhpojy5
alter table artist_end_area_join drop constraint FKqpmbpcxmsx9horym1828a6nhm
alter table artist_end_date_join drop constraint FKgwa2a78byhej610s4bdwijdy1
alter table artist_end_date_join drop constraint FK9xnh1e0g4gykda5onwvpl96w0
alter table artist_gender_join drop constraint FKgwoqki0iuuqmivpo25dnrjmb1
alter table artist_gender_join drop constraint FKhmr79ir0dvn6l6g2k4asxe9rh
alter table artist_ref_count_join drop constraint FKlb2e7nxkf00c41ynywljxmuiy
alter table artist_ref_count_join drop constraint FKsug54x25nuu957axm0c4obs0u
alter table artist_sortname_join drop constraint FK56a9947m1dr2c1j6l52plkspq
alter table artist_sortname_join drop constraint FK6q14bw7t5sywulcx7pcu6bjcs
alter table ArtistCreditedName drop constraint FKs9buctrdceu49ll5hbk8wddwl
alter table ArtistCreditedName drop constraint FKamn4sghaewa0iy4b6y0ysdyej
alter table base_type_description_join drop constraint FKckvph0x1homuj7hn7wver3f8k
alter table base_type_description_join drop constraint FK44wmj6925gqqena2mnr2d3c0e
alter table instrument drop constraint FKewxtplg47bkypefa30wk16wkg
alter table instrument_comment_join drop constraint FKijmebsqk04tiq99kvcdq1y9m3
alter table instrument_comment_join drop constraint FK8dawlfgg0km0ofqhs7k8i10rb
alter table instrument_description_join drop constraint FK4hdpovhkn51kl5pmvlj7spj0l
alter table instrument_description_join drop constraint FKkvq50u8tmgigintxinspal853
alter table isrc_recording_join drop constraint FKdst308wec9g1r2pdgl9pu66ba
alter table isrc_recording_join drop constraint FKegxd27v48533e4ioips2v0om8
alter table label drop constraint FKqmabfbh4bw9uowqp733r6f3rb
alter table label drop constraint FK6u3ob85d3br3xccgqcuds8s7j
alter table label drop constraint FKr2pu4j9nq9q9v33kq9y23wlmt
alter table label_type_join drop constraint FK9ja53dwjckolp8oawxlt9s3gx
alter table label_type_join drop constraint FK8epec4y03bpqb2m6fjrb5ae1x
alter table Medium drop constraint FK88xlaa32r1xxpm9vykwh3675e
alter table Medium drop constraint FKkhs58g5n5bnyqr14hklutr1jc
alter table medium_count_join drop constraint FKcgodk0n0yy7b9dh033hkheu72
alter table medium_count_join drop constraint FK5gnqnfnwrqj7uuio47742wsqt
alter table medium_position_join drop constraint FK7npic7e0xpkw01dji0v59jimt
alter table medium_position_join drop constraint FKqpxdjbhc5y2t6sb9g0d6sswg2
alter table ralias_sortname_join drop constraint FKp5vufn13fu2xqsrbhqmwiopxe
alter table ralias_sortname_join drop constraint FK25ufn8bacv3csjivgb3q2q3rf
alter table recording drop constraint FKwhnq53y2fteeexfpar6558ut
alter table recording drop constraint FKp6h8vblmfp7fbvy7t07unr441
alter table recording_alias drop constraint FKf3bf0jihug16pfd3n6fksolla
alter table recording_alias drop constraint FKjlmcnxa1hoj9x47ikivshfaq
alter table recording_comment_join drop constraint FKjsf5owqpo6ok6ggkes6d0b3pb
alter table recording_comment_join drop constraint FK831sby31ef8r0j0lfsfh5nx2b
alter table release drop constraint FKrjxedvgqei5yg4s02538jeu55
alter table release_alias drop constraint FK8h783sk9tygkr28w7uaw66hgs
alter table release_alias drop constraint FKgaxu9q2lmc940ikhiq9awjwv2
alter table release_alias_begin_date_join drop constraint FK2pwnsix504rih7b9c0p2ldcu2
alter table release_alias_begin_date_join drop constraint FK8fwb728l8xka6plxvd5ioam9v
alter table release_alias_end_date_join drop constraint FK7q6nahiooqujaombbgcbdof2e
alter table release_alias_end_date_join drop constraint FKh23905t8qli78gtd54skm2k32
alter table release_alias_locale_join drop constraint FKfu08i10orqtp60yubiuxco5ug
alter table release_alias_locale_join drop constraint FKfi3muh2yf67v2e3aavs7o23iy
alter table release_alias_sortname_join drop constraint FKk0b8uym87fp1se4cwbp8efudx
alter table release_alias_sortname_join drop constraint FK47aqy9lhj7y73lnygfx8i5wbv
alter table release_barcode_join drop constraint FK11ycaqp6hwmm3vvel4pei3hb3
alter table release_barcode_join drop constraint FK1ohu8rea5r4bflvjfo52wuiak
alter table release_catalog_join drop constraint FKo6cknv37kwvahw8kip26eaipv
alter table release_catalog_join drop constraint FK5lf20xpd4730xlr6xthgqj3jr
alter table release_comment_join drop constraint FKpum7hvj1bfx68kckhqnk068ow
alter table release_comment_join drop constraint FKaso5up8i49s07ak8mqb1w13bo
alter table release_group drop constraint FKjhugaa7xl4008xcscrx21v8iw
alter table release_group drop constraint FK9co461y510dgpqygvhigvgcko
alter table release_group_comment_join drop constraint FK6q5lnk9mj3q1qr8du8tuvjji9
alter table release_group_comment_join drop constraint FK1b65qv88y0187bhxl42m72kjx
alter table release_group_join drop constraint FK9pttnpev0leoq0vx353763urk
alter table release_group_join drop constraint FKe8w2lu5p1r45yhxl3jtn9hcua
alter table release_label drop constraint FKal3q7rkxjcxvpt0yehl9t495x
alter table release_language_join drop constraint FKk3hvg4y9h946ow3b83bt4xvgo
alter table release_language_join drop constraint FKa341slnl3qhxi6q6jn432b3yy
alter table release_packaging_join drop constraint FKx49q7bbkt5gfvxat10i9gyfc
alter table release_packaging_join drop constraint FK6bi5mttra2txy9rmevfarpqg5
alter table release_status_join drop constraint FK5t2s72heb037fymqnesmldax6
alter table release_status_join drop constraint FKbksyuuyoqsjyd16h15dm0muw
alter table releaselable_label_join drop constraint FK23bywtxvkwddnuvl7a0385hsv
alter table releaselable_label_join drop constraint FK89lf519jsmem1p5albfqo9f7v
alter table track drop constraint FKcbmq3cor34r184u84jtfhiw1r
alter table track_length_join drop constraint FKclg3rc7jynq5lx20ojjqdlj3
alter table track_length_join drop constraint FK3aj1gvdufrwb9snay9cy91t53
alter table track_number_join drop constraint FKmwwixblea4b54nrbc2i3ppbut
alter table track_number_join drop constraint FKjfj36ofn0l3no50vutks0ha5x
alter table track_position_join drop constraint FKf2dsts4egfuibtotwmjbmf3tn
alter table track_position_join drop constraint FKptd32j597vii6l8900688trkt
alter table work drop constraint FK6sdty0tnnwtb8wguhqwc0vnq0
alter table work_comment_join drop constraint FKhgg71w0ba92vpbyqpi9lsgtr3
alter table work_comment_join drop constraint FKmpkos9osoygvrnn497u2utqgv
drop table if exists area cascade
drop table if exists area_begin_date_join cascade
drop table if exists area_comment_join cascade
drop table if exists area_end_date_join cascade
drop table if exists AreaComment cascade
drop table if exists artist cascade
drop table if exists artist_alias cascade
drop table if exists artist_alias_begin_date_join cascade
drop table if exists artist_alias_end_date_join cascade
drop table if exists artist_alias_join cascade
drop table if exists artist_alias_locale_join cascade
drop table if exists artist_alias_sortname_join cascade
drop table if exists artist_alias_type_join cascade
drop table if exists artist_area_join cascade
drop table if exists artist_begin_area_join cascade
drop table if exists artist_begin_date_join cascade
drop table if exists artist_comment_join cascade
drop table if exists artist_credit cascade
drop table if exists artist_credit_count_join cascade
drop table if exists artist_credit_name_position_join cascade
drop table if exists artist_credit_name_rel cascade
drop table if exists artist_end_area_join cascade
drop table if exists artist_end_date_join cascade
drop table if exists artist_gender_join cascade
drop table if exists artist_ref_count_join cascade
drop table if exists artist_sortname_join cascade
drop table if exists ArtistComment cascade
drop table if exists ArtistCreditedName cascade
drop table if exists bar_code_base cascade
drop table if exists base_type cascade
drop table if exists base_type_description_join cascade
drop table if exists begin_dates cascade
drop table if exists description_base cascade
drop table if exists end_dates cascade
drop table if exists instrument cascade
drop table if exists instrument_comment_join cascade
drop table if exists instrument_description_join cascade
drop table if exists InstrumentComment cascade
drop table if exists isrc cascade
drop table if exists isrc_recording_join cascade
drop table if exists label cascade
drop table if exists label_type_join cascade
drop table if exists language cascade
drop table if exists locale_base cascade
drop table if exists long_count_base cascade
drop table if exists long_number_base cascade
drop table if exists long_position_base cascade
drop table if exists Medium cascade
drop table if exists medium_count_join cascade
drop table if exists medium_format cascade
drop table if exists medium_position_join cascade
drop table if exists ralias_sortname_join cascade
drop table if exists recording cascade
drop table if exists recording_alias cascade
drop table if exists recording_comment_join cascade
drop table if exists recording_lengthy_base cascade
drop table if exists RecordingComment cascade
drop table if exists release cascade
drop table if exists release_alias cascade
drop table if exists release_alias_begin_date_join cascade
drop table if exists release_alias_end_date_join cascade
drop table if exists release_alias_locale_join cascade
drop table if exists release_alias_sortname_join cascade
drop table if exists release_barcode_join cascade
drop table if exists release_catalog_join cascade
drop table if exists release_comment_join cascade
drop table if exists release_group cascade
drop table if exists release_group_comment_join cascade
drop table if exists release_group_join cascade
drop table if exists release_label cascade
drop table if exists release_label_catalog cascade
drop table if exists release_language_join cascade
drop table if exists release_packaging cascade
drop table if exists release_packaging_join cascade
drop table if exists release_status cascade
drop table if exists release_status_join cascade
drop table if exists ReleaseComment cascade
drop table if exists ReleaseGroupComment cascade
drop table if exists releaselable_label_join cascade
drop table if exists sort_name_base cascade
drop table if exists string_number_base cascade
drop table if exists track cascade
drop table if exists track_length_join cascade
drop table if exists track_number_join cascade
drop table if exists track_position_join cascade
drop table if exists TrackLength cascade
drop table if exists work cascade
drop table if exists work_comment_join cascade
drop table if exists WorkComment cascade
